import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/layout/navbar";

const fontSans = localFont({
  src: [
    {
      path: "../assets/fonts/Archivo-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../assets/fonts/Archivo-Italic.woff2",
      weight: "400",
      style: "italic",
    },
    {
      path: "../assets/fonts/Archivo-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../assets/fonts/Archivo-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-archivo",
});

export const metadata: Metadata = {
  title: "EngTech Engineering Services",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("font-archivo", fontSans.variable)}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
